version: '3.8'

services:

  db:
    image: postgres:15
    container_name: bus_db
    environment:
      POSTGRES_DB: busticketbookingsystem
      POSTGRES_USER: shashvatyadav
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: bus_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/busticketbookingsystem
      SPRING_DATASOURCE_USERNAME: shashvatyadav
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: YzN0QnBXR2Y4eFhJYVZVaWdVQ1pPaWZkR3h4R3JqR0lWZQ==

volumes:
  postgres_data: