spring.application.name=busTicketBookingSystem

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/busticketbookingsystem}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME :shashvatyadav}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD :root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:Z0FvYkNqR3lYd1hFZk1VbEtxU1J5V2JrTnBUd1ZsZ1JzT3JQd1h4Z1hWQm5TZA==}
jwt.expiration=86400000